# Specific libraries
require(shiny)
require(shinythemes)
require(shinycssloaders)
require(shinyjs)
require(shinyWidgets)
require(shinydashboard)
require(shinydashboardPlus)
require(data.table)
require(plotly)
require(ggplot2)
require(dplyr)
require(DT)
require(scales)
require(parallel)